data_path: DIV2K_valid_HR/ # Change this to the actual path
model_d: 56
model_s: 12
model_m: 4
lr_init: 0.001
epochs: 200  # Adjusted to run for 200 epochs
batch_size: 10
steps_per_epoch: 4  # Adjust this to a value suitable for your dataset size
val_batch_size: 10
validation_steps: 4   # Adjust this to a value suitable for your validation dataset size
weights_fn: "weights/model_{epoch:05d}.h5"

